### ISSUE TITLE
Version 2.0.0 is crashing 

### ISSUE THREAD

**Issue by yoavgray** [square/radiography#119]
We've had a lot of crashes coming from this library on **Android 11 and vivo devices**:
```
Caused by: java.lang.NoSuchFieldException: No field mKeyedTags in class Landroid/view/View; (declaration of 'android.view.View' appears in /system/framework/framework.jar!classes3.dex)
	at java.lang.Class.getDeclaredField(Class.java)
	at radiography.internal.ComposeViewsKt.<clinit>(ComposeViewsKt.java:14)
	at radiography.internal.ComposeViewsKt.isComposeAvailable(ComposeViewsKt.java:0)
	at radiography.ViewStateRenderers.<clinit>(ViewStateRenderers.java:58)
```

The offending usage is:
```
ImmutableList<ViewStateRenderer> renderers =
    ImmutableList.of(
        ViewStateRenderers.ViewRenderer,
        ViewStateRenderers.textViewRenderer(true, 128),
        ViewStateRenderers.CheckableRenderer);
```

Can you please advise how to handle this?

**Comment by pyricau** [comment]
Checking if compose is available by calling `ComposeViews.isComposeAvailable` causes the loading of the `ComposeViews` which causes the init of the `VIEW_KEYED_TAGS_FIELD` field:

```
private val VIEW_KEYED_TAGS_FIELD = View::class.java.getDeclaredField("mKeyedTags")
```

https://github.com/square/radiography/blob/main/radiography/src/main/java/radiography/internal/ComposeViews.kt#L15

This private field was added in 2011 https://cs.android.com/android/_/android/platform/frameworks/base/+/7db82acd8151684a886d4725ddf2790ef3a2f80e:core/java/android/view/View.java;dlc=e94d950d122005bb10e11dd18b6029d0108f2fbe

cc @zach-klippenstein we should probably do two things:

1) maybe don't init the rest of the class helpers when compose isn't in the classpath
2) Degrade gracefully if we can't find this field?

**Comment by zach-klippenstein** [comment]
We should definitely just fail gracefully if it's not found, all this reflection stuff should be as forgiving as possible.

**Comment by yoavgray** [comment]
Thank you for taking a look and thanks for this library.

**Comment by zach-klippenstein** [comment]
If this private field was added in 2011, but @yoavgray is seeing crashes on Android 11, which definitely has this field. I guess just vivo devices don't?

**Comment by Ashok-Varma** [comment]
Hi @zach-klippenstein / @pyricau any timeline on when this fix will be released ?

**Comment by zach-klippenstein** [comment]
Planning to release today.

**Comment by zach-klippenstein** [comment]
Done: https://github.com/square/radiography/releases/tag/v2.2.0
