### ISSUE TITLE
Misleading subtitle (!?): Text-ray goggles for your Android views.

### ISSUE THREAD

**Issue by jiayounokim** [square/radiography#126]
It is said in README that the project has Jetpack Compose support as well. But the subtitle limits the scope to Android View. It gives wrong impression that it only works with the View system of Android.

**Comment by pyricau** [comment]
@zach-klippenstein should we change to `Text-ray goggles for your Android UI` ?

**Comment by zach-klippenstein** [comment]
Changed the repo description and PR is up for subtitle. I'll merge later today, assuming I didn't. break the tests 😉
