### ISSUE TITLE
Rename textViewRenderer(showTextValue = true) to textViewRenderer(renderText = true)

### ISSUE THREAD

**Issue by pyricau** [square/radiography#73]

**Comment by zach-klippenstein** [comment]
If we're going to do this, we need to do it before the final release. I think we settled on `renderText`

**Comment by pyricau** [comment]
I totally thought I'd done this but I must have been dreaming.

**Comment by zach-klippenstein** [comment]
`textViewRenderer(renderText = false)` kind of looks like a no-op – the subtle distinction between “text” and “text view” is too important imo. “text value” and “text view” is a little more contrastive I think, would you agree?

```kotlin
public fun textViewRenderer(
    renderTextValue: Boolean = false,
    textValueMaxLength: Int = Int.MAX_VALUE
  )
```

Either way, we should use the same term in both params.
