### ISSUE TITLE
Suitable to include in non-fatal tracking?

### ISSUE THREAD

**Issue by ubuntudroid** [square/radiography#96]
Just a question, no bug report: 

As radiography scans the whole view hierarchy and does its magic on every node, would you consider it suitable for logging for non-fatals, that is e.g. when reporting warnings to your favourite crash tracking tool? Or is the performance overhead too big and could cause jank/stutters etc.? As you guys have been using it for years in your apps you likely have quite reliable data about that or at least a solid gut feeling. ;)

**Comment by pyricau** [comment]
It's not super cheap but not too expensive either. View hierarchy traversals happen on every redraw :) . 

The only thing to be careful about here is that if the call if not from the main thread, then it'll block until the main thread has rendered the view hierarchy to string. So if logging warnings from background threads you might block these background threads for a bit.
